# Generated by Django 5.2.1 on 2025-05-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
