# Generated by Django 5.2.1 on 2025-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('midi_limit', models.IntegerField(default=150)),
                ('soir_limit', models.IntegerField(default=150)),
            ],
        ),
    ]
